### ISSUE TITLE
No wheels for Python 3.11 and 3.12

### ISSUE THREAD

**Issue by jsolbrig** [sbrodehl/pyPublicDecompWT#5]
Currently there are no wheels for Python 3.11 and 3.12. Would it be possible to add those to `cibuildwheel.yml`?

**Comment by sbrodehl** [comment]
Hi @jsolbrig !

Thanks for reaching out, of course we can add newer versions!
Would you like to add those and open a PR?

Best,
@sbrodehl

**Comment by sbrodehl** [comment]
I have added the newer python versions.
Please let me know if you need anything else!

Best,
@sbrodehl

**Comment by jsolbrig** [comment]
@sbrodehl Thank you! I had actually forked and implemented, but found that my jobs weren't being picked up so I couldn't test what I did.
